language: python
python:
  - "3.4"
install:
  - pip install -r dependencies.txt
  - pip install flake8
before_script:
  - "flake8 --show-source --max-line-length=80 --statistics --builtins=_ pubkey"
script:
  - python pubkey/pubkey.py --help
  - python pubkey/pubkey.py --version
