language: python
python:
  - "3.4"
  - "3.5"
  - "pypy3"
os:
  - linux
  - osx
install:
  - pip install flake8
  - pip install coveralls
before_script:
  - "flake8 --show-source --max-line-length=80 --statistics --builtins=_ pubkey"
script:
  - python setup.py install
  - python setup.py sdist
  - coverage run --source=pubkey pubkey.py --help
  - coverage run --source=pubkey pubkey.py --version
  - coverage run --source=pubkey pubkey.py --debug --time 1 --key ./tests/id_rsa.pub
  - coverage run --source=pubkey pubkey.py --debug --auto --time 1 --key ./tests/id_rsa.pub
after_success:
  - coveralls
deploy:
  branches:
    only:
      - deploy-test
